#!/usr/bin/env python3
"""Sync Sphinx docs into Hugo content directory.

Reads docs/source_en and docs/source_zh, converts Markdown files to
Hugo-compatible format (adds front matter), and writes them into
twinkle-web/content/docs/usage-guide/ and twinkle-web/content/docs/components/.

Run from twinkle-web/ directory:
    python3 scripts/sync-docs.py

This script is invoked automatically by `pnpm dev` and `pnpm build`.
It should NOT be gitignored — only the generated output directories are.
"""

import os
import re
import shutil
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
WEB_ROOT = SCRIPT_DIR.parent                       # twinkle-web/


def find_docs_root() -> Path:
    """Find the docs/ directory by searching parent directories.

    twinkle-web may live as a symlink inside the twinkle repo, or as a
    sibling directory. We try multiple strategies.
    """
    # Strategy 1: sibling of web root (twinkle-web and twinkle are siblings)
    candidate = WEB_ROOT.parent / "twinkle" / "docs"
    if candidate.exists() and (candidate / "source_en").exists():
        return candidate

    # Strategy 2: walk up from the *unresolved* script path
    raw_script = Path(__file__).parent.parent  # twinkle-web/ (unresolved)
    for parent in [raw_script.parent, raw_script.parent.parent]:
        candidate = parent / "docs"
        if candidate.exists() and (candidate / "source_en").exists():
            return candidate

    # Strategy 3: environment variable
    env_docs = os.environ.get("TWINKLE_DOCS_DIR")
    if env_docs:
        p = Path(env_docs)
        if p.exists():
            return p

    # Strategy 4: resolved parent's parent (original logic)
    candidate = WEB_ROOT.parent / "docs"
    if candidate.exists() and (candidate / "source_en").exists():
        return candidate

    raise FileNotFoundError(
        "Cannot locate docs/ directory. Set TWINKLE_DOCS_DIR env variable "
        "or ensure docs/ is a sibling of twinkle-web/."
    )


DOCS_ROOT = find_docs_root()
DOCS_EN = DOCS_ROOT / "source_en"
DOCS_ZH = DOCS_ROOT / "source_zh"
OUT_DIR = WEB_ROOT / "content" / "docs"

# Directories that are generated by this script (cleaned on each run)
GENERATED_DIRS = ["usage-guide", "components"]

# ---------------------------------------------------------------------------
# Mapping: English directory name  ->  Chinese directory name
# ---------------------------------------------------------------------------
EN_ZH_DIR_MAP = {
    "Usage Guide":              "使用指引",
    "Components":               "组件",
    "Server and Client":        "服务端和客户端",
    "Dataset":                  "数据集",
    "Data Format":              "数据格式",
    "Data Loading":             "数据加载",
    "Template":                 "模板",
    "Preprocessor and Filter":  "预处理器和过滤器",
    "Task Processor":           "任务处理器",
    "Model":                    "模型",
    "Sampler":                  "采样器",
    "Reward":                   "奖励",
    "Advantage":                "优势",
    "Gym":                      "Gym",
    "Hub":                      "Hub",
    "Checkpoint Engine":        "检查点引擎",
    "Metrics":                  "指标",
    "Loss":                     "损失",
    "Loss Scale":               "损失缩放",
    "LRScheduler":              "LRScheduler",
    "Patch":                    "补丁",
    "Plugin":                   "组件化",
    "Kernel":                   "Kernel",
    "Training Middleware":       "训练中间件",
    "CLI":                      "CLI",
    "Notifier":                 "通知器",
    "Agentic":                  "Agentic",
    "TUI":                      "TUI",
}

# Chinese directory title -> English directory title (for display)
ZH_SECTION_TITLES = {v: k for k, v in EN_ZH_DIR_MAP.items()}

# ---------------------------------------------------------------------------
# Title overrides: slug -> (en_title, zh_title)
# Prevents sync from overwriting manually chosen titles.
# ---------------------------------------------------------------------------
TITLE_OVERRIDES = {
    "usage-guide/quick-start": ("Training Guide", "训练指南"),
}

# ---------------------------------------------------------------------------
# Hugo slug helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    """Convert a directory/file name to a Hugo-friendly slug."""
    s = name.lower().strip()
    s = re.sub(r"[_ ]+", "-", s)          # spaces / underscores -> hyphens
    s = re.sub(r"[^a-z0-9\-.]", "", s)    # strip non-ascii
    s = re.sub(r"-{2,}", "-", s)          # collapse double hyphens
    return s.strip("-")


def extract_title_from_md(content: str) -> str:
    """Return the first H1 heading from Markdown content, or ''."""
    for line in content.splitlines():
        m = re.match(r"^#\s+(.+)", line)
        if m:
            return m.group(1).strip()
    return ""


def strip_first_heading(content: str) -> str:
    """Remove the first H1 heading line (Hugo uses front-matter title)."""
    lines = content.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if re.match(r"^#\s+", line):
            # Also strip the blank line right after if present
            end = i + 1
            if end < len(lines) and lines[end].strip() == "":
                end += 1
            return "".join(lines[:i] + lines[end:])
    return content


# ---------------------------------------------------------------------------
# Link rewriting
# ---------------------------------------------------------------------------

# Mapping: broken relative path pattern -> corrected path
# Supports both exact matches and regex-based rewrites
LINK_REWRITES = {
    # Chinese paths -> Hugo slugified paths
    "./服务端和客户端/Twinkle客户端.md": "../server-and-client/twinkle-client/",
    "../服务端和客户端/服务端.md": "../server-and-client/server/",
    "./可观测化.md": "../observability/",
    "./训练服务.md": "../../guide/taas/",
    # English paths with spaces/wrong case -> slugified
    "./Server%20and%20Client/Twinkle-Client.md": "../server-and-client/twinkle-client/",
    "./Server and Client/Twinkle-Client.md": "../server-and-client/twinkle-client/",
    "../Server%20and%20Client/Server.md": "../server-and-client/server/",
    "../Server and Client/Server.md": "../server-and-client/server/",
    "./Train-as-a-Service.md": "../../guide/taas/",
    "./Observability.md": "../observability/",
    # Cookbook source file -> GitHub URL
    "../../../cookbook/server_mode/twinkle/self_host/self_cognition.py":
        "https://github.com/modelscope/twinkle/blob/main/cookbook/client/twinkle/self_host/self_cognition.py",
}


def rewrite_links(content: str) -> str:
    """Rewrite broken internal links to correct Hugo paths.
    
    Handles:
    1. Exact path rewrites from LINK_REWRITES mapping
    2. Case-insensitive .md references within the same directory (slugify them)
    """
    def replace_link(match):
        full_match = match.group(0)
        text = match.group(1)
        target = match.group(2)
        
        # Check exact rewrites (including URL-decoded version)
        from urllib.parse import unquote
        decoded = unquote(target)
        if target in LINK_REWRITES:
            return f"[{text}]({LINK_REWRITES[target]})"
        if decoded in LINK_REWRITES:
            return f"[{text}]({LINK_REWRITES[decoded]})"
        
        # Auto-slugify .md references in the same directory
        # e.g. "GRPOAdvantage.md" -> "grpoadvantage/"
        if target.endswith(".md") and "/" not in target:
            slug = slugify(target[:-3])
            return f"[{text}]({slug}/)"
        
        # Slugify relative .md with single directory prefix
        # e.g. "Quick-Start.md" -> "quick-start/"
        if target.endswith(".md") and target.count("/") == 0:
            slug = slugify(target[:-3])
            return f"[{text}]({slug}/)"
        
        return full_match
    
    return re.sub(r'\[([^\]]*)\]\(([^)]+)\)', replace_link, content)

def parse_toctree(rst_path: Path) -> tuple[str, list[str]]:
    """Parse an index.rst and return (section_title, [entry_paths]).

    entry_paths are the raw values from the toctree directive, e.g.
    "Dataset.md" or "Server and Client/index.rst".
    """
    text = rst_path.read_text(encoding="utf-8")
    # Section title is the first non-empty, non-directive line
    title = ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("..") and not stripped.startswith(":") \
                and not stripped.startswith("*") and "=====" not in stripped:
            title = stripped
            break

    # Collect all toctree entries (across multiple toctree directives)
    all_entries: list[str] = []
    in_toctree = False
    found_entry = False
    for line in text.splitlines():
        if ".. toctree::" in line:
            in_toctree = True
            found_entry = False
            continue
        if in_toctree:
            stripped = line.strip()
            if stripped.startswith(":"):
                continue
            if stripped == "":
                if found_entry:
                    in_toctree = False
                continue
            all_entries.append(stripped)
            found_entry = True

    return title, all_entries


# ---------------------------------------------------------------------------
# Core sync logic
# ---------------------------------------------------------------------------

def add_front_matter(content: str, title: str, weight: int,
                     extra: dict | None = None) -> str:
    """Prepend Hugo YAML front matter to Markdown content."""
    fm_lines = ["---"]
    # Escape quotes in title
    safe_title = title.replace('"', '\\"')
    fm_lines.append(f'title: "{safe_title}"')
    fm_lines.append(f"weight: {weight}")
    if extra:
        for k, v in extra.items():
            if isinstance(v, bool):
                fm_lines.append(f"{k}: {'true' if v else 'false'}")
            elif isinstance(v, str):
                fm_lines.append(f'{k}: "{v}"')
            else:
                fm_lines.append(f"{k}: {v}")
    fm_lines.append("---")
    fm_lines.append("")
    return "\n".join(fm_lines) + content


def write_index(out_dir: Path, title: str, weight: int,
                subtitle: str = "", zh_title: str = "",
                sidebar_open: bool = True):
    """Write _index.md and _index.zh.md for a Hugo section."""
    out_dir.mkdir(parents=True, exist_ok=True)

    # English _index.md
    body = f"\n{subtitle}\n" if subtitle else "\n"
    lines = [
        "---",
        f'title: "{title}"',
        f"weight: {weight}",
    ]
    if sidebar_open:
        lines.append("sidebar:")
        lines.append("  open: true")
    lines += ["---", "", body]
    # Add toc shortcode to list child pages
    lines.append("{{< list-children >}}")
    lines.append("")
    (out_dir / "_index.md").write_text("\n".join(lines), encoding="utf-8")

    # Chinese _index.zh.md
    display = zh_title or title
    lines_zh = [
        "---",
        f'title: "{display}"',
        f"weight: {weight}",
    ]
    if sidebar_open:
        lines_zh.append("sidebar:")
        lines_zh.append("  open: true")
    lines_zh += ["---", "", body]
    lines_zh.append("{{< list-children >}}")
    lines_zh.append("")
    (out_dir / "_index.zh.md").write_text("\n".join(lines_zh), encoding="utf-8")


def sync_md_file(src_en: Path, src_zh: Path | None,
                 dest_dir: Path, weight: int):
    """Copy one English .md (and its Chinese counterpart) into dest_dir."""
    dest_dir.mkdir(parents=True, exist_ok=True)

    content_en = src_en.read_text(encoding="utf-8")
    title = extract_title_from_md(content_en)
    if not title:
        title = src_en.stem

    slug = slugify(src_en.stem) + ".md"

    # Check title overrides (key = relative path under OUT_DIR without .md)
    override_key = str(dest_dir.relative_to(OUT_DIR) / slugify(src_en.stem))
    if override_key in TITLE_OVERRIDES:
        title = TITLE_OVERRIDES[override_key][0]

    # Strip the first heading since Hugo uses front-matter title
    body = strip_first_heading(content_en)
    # Rewrite broken links
    body = rewrite_links(body)
    out_en = add_front_matter(body, title, weight)

    (dest_dir / slug).write_text(out_en, encoding="utf-8")

    # Chinese version
    if src_zh and src_zh.exists():
        content_zh = src_zh.read_text(encoding="utf-8")
        title_zh = extract_title_from_md(content_zh) or title
        # Apply Chinese title override
        if override_key in TITLE_OVERRIDES:
            title_zh = TITLE_OVERRIDES[override_key][1]
        body_zh = strip_first_heading(content_zh)
        # Rewrite broken links
        body_zh = rewrite_links(body_zh)
        out_zh = add_front_matter(body_zh, title_zh, weight)
        zh_slug = slugify(src_en.stem) + ".zh.md"
        (dest_dir / zh_slug).write_text(out_zh, encoding="utf-8")


def build_en_zh_file_map() -> dict:
    """Build a complete mapping from English source path to Chinese path.

    Walks both root index.rst files and matches entries by position within
    each toctree. Recurses into sub-section index.rst files.
    Returns: {Path(en_md_file): Path(zh_md_file)}
    """
    mapping: dict[Path, Path] = {}

    en_root_index = DOCS_EN / "index.rst"
    zh_root_index = DOCS_ZH / "index.rst"
    if not en_root_index.exists() or not zh_root_index.exists():
        return mapping

    _, en_entries = parse_toctree(en_root_index)
    _, zh_entries = parse_toctree(zh_root_index)

    # Group entries by their top-level section directory
    def group_by_section(entries: list[str]) -> dict[str, list[str]]:
        out: dict[str, list[str]] = {}
        for e in entries:
            top = e.split("/", 1)[0]
            out.setdefault(top, []).append(e)
        return out

    en_groups = group_by_section(en_entries)
    zh_groups = group_by_section(zh_entries)

    # Match each English top-level section to its Chinese counterpart
    for en_section, en_list in en_groups.items():
        zh_section = EN_ZH_DIR_MAP.get(en_section)
        if not zh_section or zh_section not in zh_groups:
            continue
        zh_list = zh_groups[zh_section]
        # Match by position
        for en_entry, zh_entry in zip(en_list, zh_list):
            en_path = DOCS_EN / en_entry
            zh_path = DOCS_ZH / zh_entry
            if en_entry.endswith(".md") and zh_entry.endswith(".md"):
                if en_path.exists() and zh_path.exists():
                    mapping[en_path] = zh_path
            elif en_entry.endswith("index.rst") and zh_entry.endswith("index.rst"):
                # Recurse into sub-section
                _recurse_section_map(en_path, zh_path, mapping)

    return mapping


def _recurse_section_map(en_index: Path, zh_index: Path,
                          mapping: dict[Path, Path]):
    """Recurse into matched sub-section index.rst pair."""
    if not en_index.exists() or not zh_index.exists():
        return
    _, en_entries = parse_toctree(en_index)
    _, zh_entries = parse_toctree(zh_index)
    en_dir = en_index.parent
    zh_dir = zh_index.parent
    # Filter to only .md and index.rst entries (in declaration order)
    for en_entry, zh_entry in zip(en_entries, zh_entries):
        en_path = en_dir / en_entry
        zh_path = zh_dir / zh_entry
        if en_entry.endswith(".md") and zh_entry.endswith(".md"):
            if en_path.exists() and zh_path.exists():
                mapping[en_path] = zh_path
        elif en_entry.endswith("index.rst") and zh_entry.endswith("index.rst"):
            _recurse_section_map(en_path, zh_path, mapping)


def process_section(en_section_dir: Path, out_base: Path,
                    section_weight: int, en_zh_map: dict):
    """Recursively process an English section directory."""
    index_rst = en_section_dir / "index.rst"
    if not index_rst.exists():
        return

    section_name = en_section_dir.name
    section_slug = slugify(section_name)
    out_dir = out_base / section_slug

    rst_title, entries = parse_toctree(index_rst)
    zh_title = EN_ZH_DIR_MAP.get(section_name, "")

    write_index(out_dir, rst_title or section_name, section_weight,
                zh_title=zh_title)

    sub_weight = 1
    for entry in entries:
        entry_path = en_section_dir / entry
        if entry.endswith("index.rst"):
            # Sub-section
            sub_dir = entry_path.parent
            process_section(sub_dir, out_dir, sub_weight, en_zh_map)
        elif entry.endswith(".md"):
            if entry_path.exists():
                zh_file = en_zh_map.get(entry_path)
                sync_md_file(entry_path, zh_file, out_dir, sub_weight)
        sub_weight += 1


def process_top_level_section(section_name: str, en_base: Path,
                              out_base: Path, section_weight: int,
                              en_zh_map: dict):
    """Process a top-level section (Usage Guide or Components)."""
    en_dir = en_base / section_name
    if not en_dir.exists():
        print(f"  [SKIP] {en_dir} does not exist")
        return

    slug = slugify(section_name)
    out_dir = out_base / slug
    zh_name = EN_ZH_DIR_MAP.get(section_name, section_name)

    # Parse top-level index.rst
    top_index = DOCS_EN / "index.rst"
    _, top_entries = parse_toctree(top_index)

    # Get entries for this section from the main index
    section_entries = [e for e in top_entries
                       if e.startswith(f"{section_name}/")]

    write_index(out_dir, section_name, section_weight,
                zh_title=zh_name, sidebar_open=True)

    sub_weight = 1
    for entry in section_entries:
        entry_path = DOCS_EN / entry
        if entry.endswith("index.rst"):
            # It's a sub-section directory
            sub_dir = entry_path.parent
            process_section(sub_dir, out_dir, sub_weight, en_zh_map)
        elif entry.endswith(".md"):
            if entry_path.exists():
                zh_file = en_zh_map.get(entry_path)
                sync_md_file(entry_path, zh_file, out_dir, sub_weight)
        sub_weight += 1


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print(f"[sync-docs] Syncing docs from {DOCS_EN} and {DOCS_ZH}")
    print(f"[sync-docs] Output: {OUT_DIR}")

    # Build EN -> ZH file mapping up-front
    en_zh_map = build_en_zh_file_map()
    print(f"  [MAP] Built EN->ZH mapping: {len(en_zh_map)} entries")

    # Clean generated directories
    for d in GENERATED_DIRS:
        target = OUT_DIR / d
        if target.exists():
            shutil.rmtree(target)
            print(f"  [CLEAN] {target}")

    # Process Usage Guide (weight=10, after getting-started at weight=1)
    process_top_level_section("Usage Guide", DOCS_EN,
                              OUT_DIR, section_weight=10,
                              en_zh_map=en_zh_map)

    # Process Components (weight=20)
    process_top_level_section("Components", DOCS_EN,
                              OUT_DIR, section_weight=20,
                              en_zh_map=en_zh_map)

    # Count output files
    total = sum(1 for _ in OUT_DIR.rglob("*.md")
                if any(d in str(_) for d in GENERATED_DIRS))
    print(f"[sync-docs] Done! Generated {total} files.")


if __name__ == "__main__":
    main()
